; Design module specifications

[design_type]
PCCDesign_type = G
;| Design type ('G' for 'genetic')

[population]
population_size = 10
;| Number of 'creatures' in the initial and maybe future populations
survival_rate = 0.1
;| The ratio (population_size/ survival_rate) gives the number of considered newly created State Vectors at each calculation step

[module_output]
module_log_file = ON
; 'ON' or 'OFF' writing of technical information to the corresponding '*.log' file of the module
