; Design module specifications

[design_type]
design_mode = G
;| Design type ('G' for 'genetic')

[genetic_algorithm]
goal_function_id = Ic
; 'T' - testing function, 'Sc' - Configuration entropy, 'Ic' - Irradiation kinetics
cell_type = 3
; '0' - nodes, '1' - edges, '2' - faces, '3' - grains
population_size = 3
;| Number of 'creatures' in the initial and maybe future populations
genes_diversity = 4
; number of different kinds of genes {0, 1, 2, 3, ..}
; only {0, 1} for the binary case where genes_diversity = 2
mutation_rate = 0.05
; fraction of mutation in the population
crossover_rate = 0.7
; probability of acceptance
survival_rate = 0.1
;| The ratio (population_size/ survival_rate) gives the number of considered newly created State Vectors at each calculation step
max_generation_number = 10
; maximal generation as a computation limit

[module_output]
module_log_file = ON
; 'ON' or 'OFF' writing of technical information to the corresponding '*.log' file of the module
