; KINETIC module specifications

[kinetic_mode]
node_kinetic_mode = N
edge_kinetic_mode = N
face_kinetic_mode = I
polyhedra_kinetic_mode = N
;| Kinetic type ('N' for "not active", 'D' for 'dislocation', 'C' for 'corrosion', 'I' for 'irradiation', and 'T' for deformation twins) of different k-cells in a PCC

[material_id]
mat_id = steel
; material ID as it is written in the CPD_material_database .ini file (e.g. 'nickel' and 'steel')

; Corrosion -- C -- mode
[corrosion]
corrosion_rate_coeff = 1.0
; set time scale for a kinetic process by multiplication [0,1] interval with the real time interval

kinetic_time_scale = 10.0
; use to change time step 10000

; Irradiation -- I -- mode
[irradiation]
beam_energy_flux = 1.0
; energy flux in [J/s]
beam_current = 1.0
; beam current in [particles/s]
energy_dissipation_rate = 1.0
; coefficient for the exponential energy dissipation rate with material depth



; DISLOCATIONS -- D -- mode
[initial]
disloc_density = 10E12
;| Initial dislocation density, Units = [m^-2]
generation_rate_coeff = 0.0
;| coefficient for dislocation generation rate
annihilation_rate_coeff = 0.0
;| coefficient for dislocation annihilation rate
immobilisation_rate_coeff = 0.0
;| coefficient for dislocation immobilisation rate

[general]
Eta_energy_conversion_coeff = 0.1
;| the fraction of energy converted into defects = (1 - Taylor-Quinney factor)
ED_specific_disloc_line_energy = 8
;| dislocation energy per unit meter with units [eV/b], where 'eV' means electronvolt, and 'b' is a material Burgers vector

[module_output]
module_log_file = ON
; 'ON' or 'OFF' writing of technical information to the corresponding '*.log' file of the module
