;///************************************************************************************************///
;///************************   Polytopal Cell Complex (PCC) Processing Design :: (CPD code) (c)   *///
;///*                                        Version 5.0 | 03/011/2025                           *///
;///*********************************************************************************************///
;///*    Code source:    https://github.com/PRISBteam/PCC_Processing_Design/                   *///
;///*    PCC sources:    https://materia.team/                                                *///
;///******************************************************************************************///
;///*****************************************************************************************///

[execution_mode]
mode = LIST
; LIST', 'TUTORIAL', 'PERFORMANCE_TEST', or 'TASK' simulation modes
; * 'LIST' is the basic implementation mode executing all active ('ON' in the list below) project modules sequentially;
; * 'TUTORIAL' is a specific educational mode for the introductory code exploration;
; * 'PERFORMANCE_TEST' is a special test for a computer's performance and its ability to work with large PCCs, and
; * 'TASK' mode runs user 'task' scripts from 'tasks/*.cpp' files. They may employ any necessary modules and functions alongside CPD project libraries.

simulation_tasks_dir=/../src/tasks/
; path to the specific directory containing 'tasks/*.cpp' source file with user code. Only active in the 'TASK' execution mode.

[modules]
PCC_Subcomplex=OFF
; creates PCC subcomplexes of different types
PCC_Multiphysics=OFF
; set energies of various PCC cells
PCC_Processing=ON
; creates k-cells labelling
PCC_Kinetics=OFF
; creates p-cells' history of changing their special generated types as the result of a kinetic process
PCC_Design=OFF
; compute optimised state vectors according to some goal functions
PCC_Characterisation=OFF
; performs entropic (statistical) and component (spectral) analyses of special, induced, and generated PCC cells
PCC_Writer=OFF
; outputs data to files

[general]
PCC_dimension = 3
; problem/PCC dimension is the maximal 'p' integer value of the PCC's p-cells (1, 2, or 3 - for graphs, plane cuts, and bulk tessellations, respectively)

pcc_source_dir = ../PCC_sources/Voronoi_1k/
; path to the source directory containing PCC (MUST end with a '/' sign)

pcc_standard = pcc1s
; ID of the used computation PCC standard (see technical documentation of the project) for the PCC files contained in the directory 'source_dir'. The ID for the first PCC standard is 'pcc1s'

output_dir = ../results/
; path to the output directory containing the code execution results