;///************************************************************************************************///
;///************************   Polytopal Cell Complex (PCC) Processing Design :: (CPD code) (c)   *///
;///*                                        Version 5.0 | 12/06/2025                            *///
;///*********************************************************************************************///
;///*    Code source:    https://github.com/PRISBteam/PCC_Processing_Design/                   *///
;///*    PCC sources:    https://materia.team/                                                *///
;///******************************************************************************************///
;///*****************************************************************************************///

[execution_mode]
mode = LIST
; LIST', 'TUTORIAL', 'PERFORMANCE_TEST' or 'TASK' simulation modes
; * 'LIST' is the basic implementation mode for the execution one by one all the active ('ON' in the list below) project modules;
; * 'TUTORIAL' is a specific educational mode for the first acquaintance with the code;
; * 'PERFORMANCE_TEST' is a special test for a computer's performance and its ability to work with large PCCs, and
; * 'TASK' is a mode, where user-defined task scripts described in the separate 'tasks/*.cpp' files are included and employ all the additional necessary modules and functions only from the CPD project libraries.

simulation_tasks_dir=/../src/tasks/
; path to the specific directory contained 'tasks/*.cpp' source file with the user-written code. Active only for the 'TASK' execution mode.

[modules]
PCC_Subcomplex=ON
; creates PCC subcomplexes of different types
PCC_Multiphysics=ON
; set energies of various PCC cells
PCC_Processing=ON
; creates k-cells labelling
PCC_Kinetics=ON
; creates p-cell history of changing their special generated types as the result of a kinetic process
PCC_Design=OFF
; compute optimised state vectors according to some goal functions
PCC_Characterisation=OFF
; performs statistical and spectral analysis of the special and induced PCC cells
PCC_Writer=OFF
; outputs data to files

[general]
PCC_dimension = 3
; problem/PCC dimension is the maximal 'p' integer value of the PCC's p-cells (1, 2 or 3 - for graphs, planes and bulk tessellations, respectively)

pcc_source_dir = ../PCC_sources/Voronoi_1k/
; /Users/user/Library/CloudStorage/Dropbox/OFFICE/EGitHub/PCC_Processing_Design/CPD_2025/PCCs/Voronoi_100_sphericity/
;
; path to the source directory containing PCC (ended with '/' sign)

pcc_standard = pcc1s
; ID of the used standard (see technical documentation of the project) for the PCC files contained in the 'source_dir'. The ID for the first PCC standard is 'pcc1s'

output_dir = ../results/
; /Users/user/Library/CloudStorage/Dropbox/OFFICE/EGitHub/PCC_Processing_Design/CPD_2025/PCC_Processing_Design/results
; path to the output directory containing results of the code execution