; Multiphysics module specifications

[material_id]
Mid_matrix = nickel
;matrix| specific ID corresponding to the code-related materials database
Mid_inclusion1 = rGO
;inclusion1| specific ID corresponding to the code-related materials database

[sample_dimensions]
; in metres ; cuboid sample
lx = 0.000001
ly = 0.000001
lz = 0.000001

[time_scale]
; in seconds
multiphysics_time_scale = 0.000002

[stress_tensor]
; set stress tensor components in [MPa] (!!)
sxx = 0.0
syy = 20.0
; 20.0
szz = 0.0

sxy = 0.0
syx = 0.0
sxz = 0.0
szx = 0.0
syz = 0.0
szy = 0.0
;| homogeneous stress state: external stress tensor components

[temperature]
ambient_temperature = 300.0
; an average temperature of a material or its environment

[microcracks]
inclusion_stress_intensity_factor = 1.0
crack_stress_intensity_factor = 2.0

[macrocracks]
number_of_macrocracks = 1

crack_stress_mode = 1
; I (=1), II (=2), or III (=3) crack modes
min_crack_lenghts = 0.02
;0.02
; as fraction of the sample dimension
max_crack_lenghts = 0.2
; as fraction of the sample dimension
number_of_crack_sizes = 1
; associated with a microcrack growth
grow_direction = zz
; 'xx' - for x-axis, 'yy' - for y-axis, 'zz' - for z-axis

[module_output]
module_log_file = ON
; 'ON' or 'OFF' writing of technical information to the corresponding '*.log' file of the module
