; Ni (polycrystalline nickel)

[structural]
material_type = metal

gb_width = 1.0
; grain boundary width in [nanometres]

[thermodynamical]
mass_density = 0.0
; mass density [kg/m^3]

melting_point = 0000
; [Kelvin]

gb_cohesion_energy = 0.0
; surface energies in [J/m^2] 

[mechanical] 
Young_modulus = 210.0
; in [GPa] (!)
Poisson_ratio = 0.31
;
yield_strength = 110.0
; in [MPa] (!)
strength = 400.0
; in [MPa] (!)
fracture_toughness = 130
; in [MPa*SQRT(metre)]

[corrosion_current]
low_angle_gb = 1.0
; corrosion current in LAGBs

high_angle_gb = 14.0
; corrosion current in HAGBs

sigma3_gb = 0.05
; corrosion current in twin (Sigma3) grain boundaries

[inclusions]
; [1] REDUCED GRAPHENE OXIDE (rGO) ENERGY DENSITY
gb_adhesion_energy = 0.0
; matrix-rGO grain boundary energy in [J/m^2]