; Steel (a typical steel)

[irradiation]
austenite_interface_param = 0.0005
martensite_interface_param = 0.0001
austenite_martensite_interface_param = 0.01

ferrite_interface_param = 0.01
austenite_ferrite_interface_param = 0.01
martensite_ferrite_interface_param = 0.001


[structural]
material_type = metal
gb_width = 1.0
; grain boundary width in [nanometres]
Burgers_vector = 2.8E-10
; Burgers vector of crystalline lattice in [metres]

[thermodynamical]
mass_density = 0.0
; mass density [kg/m^3]

melting_point = 0000
; [Kelvin]

gb_cohesion_energy = 0.0
; surface energies in [J/m^2] 

[mechanical] 
Young_modulus = 0.0
; in [GPa] (!)

Poisson_ratio = 0.0

yield_strength = 0.0
; in [MPa] (!)

strength = 0.0
; in [MPa] (!)

fracture_toughness = 0.0
; in [MPa*SQRT(metre)]

[inclusions]
; [1] REDUCED GRAPHENE OXIDE (rGO) ENERGY DENSITY
gb_adhesion_energy = 0.0
; matrix-rGO grain boundary energy in [J/m^2]
